# -*- coding: utf-8 -*-
"""
config.py — Rutas de las apps de la suite. Lo único que cambia entre máquinas
son estas carpetas; se pueden sobreescribir con variables de entorno.
"""
import os

# Cada app: dónde vive + por qué archivo se abre (en orden de preferencia) +
# de dónde leer su versión para mostrarla.
APPS = [
    {
        "key": "impuestos",
        "nombre": "Impuestos (IIBB + IVA)",
        "emoji": "🧮",
        "mono": "IMP",
        "desc": "Ingresos Brutos CM03 + IVA (Portal IVA, SIRCREB, retenciones, liquidación, asientos) de las 9 empresas. Reemplaza a DDJJ Impuestos y a CM03.",
        "color": "#2EE6A6",
        "env_dir": "IMPUESTOS_DIR",
        "dir": os.environ.get("IMPUESTOS_DIR", r"D:\PROYECTOS CLAUDE\impuestos"),
        "entradas": ["ejecutar.bat", "app.py"],
        "version_file": "version.py",
        "repo": "ematiromero98/impuestos",
    },
    {
        "key": "reten",
        "nombre": "Órdenes de Pago",
        "emoji": "🧾",
        "mono": 'RP',
        "desc": "Retenciones, órdenes de pago y conciliación de compras.",
        "color": "#1E8E4E",
        "env_dir": "RETENCIONESPRO_DIR",
        "dir": os.environ.get("RETENCIONESPRO_DIR", r"D:\RetencionesPro"),
        "entradas": ["run.bat", "main.py"],
        "version_file": "version.py",
        "repo": "ematiromero98/ordenes-de-pago",
    },
    {
        "key": "cobranzas",
        "nombre": "Cobranzas",
        "emoji": "💰",
        "mono": 'COB',
        "desc": "Cobranzas OSECAC: retenciones, asientos y facturación.",
        "color": "#D68910",
        "env_dir": "COBRANZAS_DIR",
        "dir": os.environ.get("COBRANZAS_DIR", r"D:\PROYECTOS CLAUDE\cobranzas-osecac"),
        "entradas": ["Iniciar Cobranzas.bat", "cobranzas_qt.py"],
        "version_file": "VERSION",
        "repo": "ematiromero98/cobranzas",
    },
    {
        "key": "facturador",
        "nombre": "Facturador Monotributistas",
        "emoji": "📄",
        "mono": 'FAC',
        "desc": "Facturación electrónica ARCA (WSFEV1).",
        "color": "#16A085",
        "env_dir": "FACTURADOR_DIR",
        "dir": os.environ.get("FACTURADOR_DIR", r"D:\PROYECTOS CLAUDE\facturador-arca"),
        "entradas": ["main.py"],
        "version_file": "VERSION",
        "repo": "ematiromero98/facturador-monotributistas",
    },
    {
        "key": "employee",
        "nombre": "Employee Pro",
        "emoji": "👥",
        "mono": 'EP',
        "desc": "Gestión de RR.HH.: legajos, ausencias, sueldos. Multiempresa.",
        "color": "#8E44AD",
        "env_dir": "EMPLOYEE_PRO_DIR",
        "dir": os.environ.get("EMPLOYEE_PRO_DIR", r"D:\PROYECTOS CLAUDE\employee-pro"),
        "entradas": ["run.bat", "main.py"],
        "version_file": "version.py",
        "repo": "ematiromero98/employee-pro",
    },
    {
        "key": "deposito",
        "nombre": "Depósito Avalos",
        "emoji": "📦",
        "mono": 'DA',
        "desc": "Control de stock del depósito de artículos de limpieza.",
        "color": "#A04000",
        "env_dir": "DEPOSITO_AVALOS_DIR",
        "dir": os.environ.get("DEPOSITO_AVALOS_DIR", r"D:\PROYECTOS CLAUDE\deposito-avalos"),
        "entradas": ["ejecutar.bat", "app.py"],
        "version_file": "version.py",
        "repo": "ematiromero98/deposito-avalos",
    },
    {
        "key": "uniformes",
        "nombre": "Depósito Uniformes",
        "emoji": "👔",
        "mono": 'DU',
        "desc": "Stock de ropa y uniformes de los empleados de seguridad (por talle, entregas con recibo y firma).",
        "color": "#2C3E50",
        "env_dir": "DEPOSITO_UNIFORMES_DIR",
        "dir": os.environ.get("DEPOSITO_UNIFORMES_DIR", r"D:\PROYECTOS CLAUDE\deposito-uniformes"),
        "entradas": ["ejecutar.bat", "app.py"],
        "version_file": "version.py",
        "repo": "ematiromero98/deposito-uniformes",
    },
    {
        "key": "juicios",
        "nombre": "Control de Juicios",
        "emoji": "⚖️",
        "mono": 'CJ',
        "desc": "Juicios y contingencias laborales de las empresas clientes.",
        "color": "#1F4E79",
        "env_dir": "JUICIOS_DIR",
        "dir": os.environ.get("JUICIOS_DIR", r"D:\control-juicios"),
        "entradas": ["run.bat", "main.py"],
        "version_file": "VERSION",
        "repo": "ematiromero98/control-juicios",
    },
    {
        "key": "contabilidad",
        "nombre": "Contabilidad",
        "emoji": "📚",
        "mono": 'CTB',
        "desc": "Libro Diario/Mayor y estados contables. Concilia contra Tango.",
        "color": "#117864",
        "env_dir": "CONTABILIDAD_DIR",
        "dir": os.environ.get("CONTABILIDAD_DIR", r"D:\contabilidad"),
        "entradas": ["run.bat", "main.py"],
        "version_file": "VERSION",
        "repo": "ematiromero98/contabilidad",
    },
    {
        "key": "conciliador",
        "nombre": "Conciliador Bancario",
        "emoji": "🏦",
        "mono": 'CB',
        "desc": "Concilia el Mayor de Tango contra el extracto del banco (BBVA).",
        "color": "#0F9D78",
        "env_dir": "CONCILIADOR_DIR",
        "dir": os.environ.get("CONCILIADOR_DIR", r"D:\PROYECTOS CLAUDE\conciliador-bancario"),
        "entradas": ["run.bat", "main.py"],
        "version_file": "VERSION",
        "repo": "ematiromero98/conciliador-bancario",
    },
    {
        "key": "ausencias",
        "nombre": "Calendario de Ausencias",
        "emoji": "📅",
        "mono": 'CA',
        "desc": "Vacaciones y licencias del equipo. Carga desde el celular.",
        "color": "#2ee6a6",
        "env_dir": "CALENDARIO_AUSENCIAS_DIR",
        "dir": os.environ.get("CALENDARIO_AUSENCIAS_DIR", r"D:\PROYECTOS CLAUDE\calendario-ausencias"),
        "entradas": ["run.bat", "main.py"],
        "version_file": "version.py",
        "repo": "ematiromero98/calendario-ausencias",
    },
    {
        "key": "veps",
        "nombre": "VEP Autónomos",
        "emoji": "🏛️",
        "mono": 'VEP',
        "desc": "Genera en tanda los VEP de Autónomos en ARCA (login + SETI).",
        "color": "#7D3C98",
        "env_dir": "VEP_AUTONOMOS_DIR",
        "dir": os.environ.get("VEP_AUTONOMOS_DIR", r"D:\arca-vep-autonomos"),
        "entradas": ["run.bat", "main.py"],
        "version_file": "VERSION",
        "repo": "ematiromero98/arca-vep-autonomos",
    },
]
